# Generated by Django 3.0.6 on 2020-08-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compression_api', '0002_auto_20200805_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
